# Pipeline for Develop PR

name: $(Date:yyyyMMdd)$(Rev:r)

trigger: none
pr:
- develop

pool:
  name: $(VMPool)

steps:
- template: Base-Steps.yml
  parameters:
    Version: $(Version-Develop)
    NugetVersion : NugetVersion-Develop
